### ISSUE TITLE
multiple ctrl-D 

### ISSUE THREAD

**Issue by ldes-cou** [arthur-trt/ft_irc#51]
server stop to answer after multiple ctrl-D

**Comment by ldes-cou** [comment]
join #riri
_:e3r8p7.clusters.42paris.fr 421 lol JOIJOIN :Unknown command_

**Comment by arthur-trt** [comment]
If you use `nc` it's not a bug. NC stop sending anything after a <Ctrl-D>, because normally a <Ctrl-D> close the connection. Can you reproduce with `telnet` ?

**Comment by arthur-trt** [comment]
Not a bug
